In [1]:
print('pandas')

pandas

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.listdir()

['.ipynb_checkpoints', '01numpy.ipynb', '02pandas.ipynb', 'data.csv']

In [8]:
df=pd.read_csv('data.csv')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [9]:
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [10]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

pd.DataFrame(mydataset)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2

In [11]:

print(pd.__version__)

2.2.3

In [13]:
arr1=[1,3,5,7,9]
myvar=pd.Series(arr1)

In [15]:
print(myvar[0])

1

In [16]:
arr1=[1,3,5,7]
myvar=pd.Series(arr1,index=['row1','row2','row3','row4'])
myvar

row1    1
row2    3
row3    5
row4    7
dtype: int64

In [18]:
myvar['row2']

np.int64(3)

In [19]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)
myvar

day1    420
day2    380
day3    390
dtype: int64

In [20]:
calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories, index = ["day1", "day2"])

print(myvar)

day1    420
day2    380
dtype: int64

In [21]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45

In [23]:
type(myvar['duration'])

pandas.core.series.Series

In [26]:
type(myvar.loc[0])
print(myvar.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [28]:
myvar.loc[[0,1]]

   calories  duration
0       420        50
1       380        40

In [29]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [30]:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

In [31]:
pd.read_csv('data.csv')

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [32]:
pd.read_csv('https://www.w3schools.com/python/pandas/data.csv.txt')

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [46]:
import urllib.request
msg='https://www.w3schools.com/python/pandas/data.csv.txt'
with (
    urllib.request.urlopen(msg) as f,
    open('data2.csv','w') as fw
    ):
    fw.write(bytes.decode(f.read(),'utf-8'))

In [47]:
print(pd.options.display.max_rows)

60

In [48]:
pd.options.display.max_rows = 9999

df = pd.read_csv('data.csv')

print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [49]:
df = pd.read_json('https://www.w3schools.com/python/pandas/data.js')

print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [50]:
msg='https://www.w3schools.com/python/pandas/data.js'
with (
    urllib.request.urlopen(msg) as f
    ):
    print(bytes.decode(f.read(),'utf-8'))

{
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60,
    "6":60,
    "7":45,
    "8":30,
    "9":60,
    "10":60,
    "11":60,
    "12":60,
    "13":60,
    "14":60,
    "15":60,
    "16":60,
    "17":45,
    "18":60,
    "19":45,
    "20":60,
    "21":45,
    "22":60,
    "23":45,
    "24":60,
    "25":60,
    "26":60,
    "27":60,
    "28":60,
    "29":60,
    "30":60,
    "31":45,
    "32":60,
    "33":60,
    "34":60,
    "35":60,
    "36":60,
    "37":60,
    "38":60,
    "39":45,
    "40":45,
    "41":60,
    "42":60,
    "43":60,
    "44":60,
    "45":60,
    "46":60,
    "47":45,
    "48":45,
    "49":60,
    "50":60,
    "51":80,
    "52":60,
    "53":60,
    "54":30,
    "55":60,
    "56":60,
    "57":45,
    "58":20,
    "59":45,
    "60":210,
    "61":160,
    "62":160,
    "63":45,
    "64":20,
    "65":180,
    "66":150,
    "67":150,
    "68":20,
    "69":300,
    "70":150,
    "71":60,
    "72":90,
    "73":150,
    "74":45,
    "75":90,
    "76":45,
    "77":45,
    "78":120,
    "79":270,
    "80":30,
    "81":45,
    "82":30,
    "83":120,
    "84":45,
    "85":30,
    "86":45,
    "87":120,
    "88":45,
    "89":20,
    "90":180,
    "91":45,
    "92":30,
    "93":15,
    "94":20,
    "95":20,
    "96":30,
    "97":25,
    "98":30,
    "99":90,
    "100":20,
    "101":90,
    "102":90,
    "103":90,
    "104":30,
    "105":30,
    "106":180,
    "107":30,
    "108":90,
    "109":210,
    "110":60,
    "111":45,
    "112":15,
    "113":45,
    "114":60,
    "115":60,
    "116":60,
    "117":60,
    "118":60,
    "119":60,
    "120":30,
    "121":45,
    "122":60,
    "123":60,
    "124":60,
    "125":60,
    "126":60,
    "127":60,
    "128":90,
    "129":60,
    "130":60,
    "131":60,
    "132":60,
    "133":60,
    "134":60,
    "135":20,
    "136":45,
    "137":45,
    "138":45,
    "139":20,
    "140":60,
    "141":60,
    "142":45,
    "143":45,
    "144":60,
    "145":45,
    "146":60,
    "147":60,
    "148":30,
    "149":60,
    "150":60,
    "151":60,
    "152":60,
    "153":30,
    "154":60,
    "155":60,
    "156":60,
    "157":60,
    "158":60,
    "159":30,
    "160":30,
    "161":45,
    "162":45,
    "163":45,
    "164":60,
    "165":60,
    "166":60,
    "167":75,
    "168":75
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102,
    "6":110,
    "7":104,
    "8":109,
    "9":98,
    "10":103,
    "11":100,
    "12":106,
    "13":104,
    "14":98,
    "15":98,
    "16":100,
    "17":90,
    "18":103,
    "19":97,
    "20":108,
    "21":100,
    "22":130,
    "23":105,
    "24":102,
    "25":100,
    "26":92,
    "27":103,
    "28":100,
    "29":102,
    "30":92,
    "31":90,
    "32":101,
    "33":93,
    "34":107,
    "35":114,
    "36":102,
    "37":100,
    "38":100,
    "39":104,
    "40":90,
    "41":98,
    "42":100,
    "43":111,
    "44":111,
    "45":99,
    "46":109,
    "47":111,
    "48":108,
    "49":111,
    "50":107,
    "51":123,
    "52":106,
    "53":118,
    "54":136,
    "55":121,
    "56":118,
    "57":115,
    "58":153,
    "59":123,
    "60":108,
    "61":110,
    "62":109,
    "63":118,
    "64":110,
    "65":90,
    "66":105,
    "67":107,
    "68":106,
    "69":108,
    "70":97,
    "71":109,
    "72":100,
    "73":97,
    "74":114,
    "75":98,
    "76":105,
    "77":110,
    "78":100,
    "79":100,
    "80":159,
    "81":149,
    "82":103,
    "83":100,
    "84":100,
    "85":151,
    "86":102,
    "87":100,
    "88":129,
    "89":83,
    "90":101,
    "91":107,
    "92":90,
    "93":80,
    "94":150,
    "95":151,
    "96":95,
    "97":152,
    "98":109,
    "99":93,
    "100":95,
    "101":90,
    "102":90,
    "103":90,
    "104":92,
    "105":93,
    "106":90,
    "107":90,
    "108":90,
    "109":137,
    "110":102,
    "111":107,
    "112":124,
    "113":100,
    "114":108,
    "115":108,
    "116":116,
    "117":97,
    "118":105,
    "119":103,
    "120":112,
    "121":100,
    "122":119,
    "123":107,
    "124":111,
    "125":98,
    "126":97,
    "127":109,
    "128":99,
    "129":114,
    "130":104,
    "131":107,
    "132":103,
    "133":106,
    "134":103,
    "135":136,
    "136":117,
    "137":115,
    "138":113,
    "139":141,
    "140":108,
    "141":97,
    "142":100,
    "143":122,
    "144":136,
    "145":106,
    "146":107,
    "147":112,
    "148":103,
    "149":110,
    "150":106,
    "151":109,
    "152":109,
    "153":150,
    "154":105,
    "155":111,
    "156":97,
    "157":100,
    "158":114,
    "159":80,
    "160":85,
    "161":90,
    "162":95,
    "163":100,
    "164":105,
    "165":110,
    "166":115,
    "167":120,
    "168":125
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127,
    "6":136,
    "7":134,
    "8":133,
    "9":124,
    "10":147,
    "11":120,
    "12":128,
    "13":132,
    "14":123,
    "15":120,
    "16":120,
    "17":112,
    "18":123,
    "19":125,
    "20":131,
    "21":119,
    "22":101,
    "23":132,
    "24":126,
    "25":120,
    "26":118,
    "27":132,
    "28":132,
    "29":129,
    "30":115,
    "31":112,
    "32":124,
    "33":113,
    "34":136,
    "35":140,
    "36":127,
    "37":120,
    "38":120,
    "39":129,
    "40":112,
    "41":126,
    "42":122,
    "43":138,
    "44":131,
    "45":119,
    "46":153,
    "47":136,
    "48":129,
    "49":139,
    "50":136,
    "51":146,
    "52":130,
    "53":151,
    "54":175,
    "55":146,
    "56":121,
    "57":144,
    "58":172,
    "59":152,
    "60":160,
    "61":137,
    "62":135,
    "63":141,
    "64":130,
    "65":130,
    "66":135,
    "67":130,
    "68":136,
    "69":143,
    "70":129,
    "71":153,
    "72":127,
    "73":127,
    "74":146,
    "75":125,
    "76":134,
    "77":141,
    "78":130,
    "79":131,
    "80":182,
    "81":169,
    "82":139,
    "83":130,
    "84":120,
    "85":170,
    "86":136,
    "87":157,
    "88":103,
    "89":107,
    "90":127,
    "91":137,
    "92":107,
    "93":100,
    "94":171,
    "95":168,
    "96":128,
    "97":168,
    "98":131,
    "99":124,
    "100":112,
    "101":110,
    "102":100,
    "103":100,
    "104":108,
    "105":128,
    "106":120,
    "107":120,
    "108":120,
    "109":184,
    "110":124,
    "111":124,
    "112":139,
    "113":120,
    "114":131,
    "115":151,
    "116":141,
    "117":122,
    "118":125,
    "119":124,
    "120":137,
    "121":120,
    "122":169,
    "123":127,
    "124":151,
    "125":122,
    "126":124,
    "127":127,
    "128":125,
    "129":151,
    "130":134,
    "131":138,
    "132":133,
    "133":132,
    "134":136,
    "135":156,
    "136":143,
    "137":137,
    "138":138,
    "139":162,
    "140":135,
    "141":127,
    "142":120,
    "143":149,
    "144":170,
    "145":126,
    "146":136,
    "147":146,
    "148":127,
    "149":150,
    "150":134,
    "151":129,
    "152":138,
    "153":167,
    "154":128,
    "155":151,
    "156":131,
    "157":120,
    "158":150,
    "159":120,
    "160":120,
    "161":130,
    "162":130,
    "163":140,
    "164":140,
    "165":145,
    "166":145,
    "167":150,
    "168":150
  },
  "Calories":{
    "0":409.1,
    "1":479.0,
    "2":340.0,
    "3":282.4,
    "4":406.0,
    "5":300.5,
    "6":374.0,
    "7":253.3,
    "8":195.1,
    "9":269.0,
    "10":329.3,
    "11":250.7,
    "12":345.3,
    "13":379.3,
    "14":275.0,
    "15":215.2,
    "16":300.0,
    "17":null,
    "18":323.0,
    "19":243.0,
    "20":364.2,
    "21":282.0,
    "22":300.0,
    "23":246.0,
    "24":334.5,
    "25":250.0,
    "26":241.0,
    "27":null,
    "28":280.0,
    "29":380.3,
    "30":243.0,
    "31":180.1,
    "32":299.0,
    "33":223.0,
    "34":361.0,
    "35":415.0,
    "36":300.5,
    "37":300.1,
    "38":300.0,
    "39":266.0,
    "40":180.1,
    "41":286.0,
    "42":329.4,
    "43":400.0,
    "44":397.0,
    "45":273.0,
    "46":387.6,
    "47":300.0,
    "48":298.0,
    "49":397.6,
    "50":380.2,
    "51":643.1,
    "52":263.0,
    "53":486.0,
    "54":238.0,
    "55":450.7,
    "56":413.0,
    "57":305.0,
    "58":226.4,
    "59":321.0,
    "60":1376.0,
    "61":1034.4,
    "62":853.0,
    "63":341.0,
    "64":131.4,
    "65":800.4,
    "66":873.4,
    "67":816.0,
    "68":110.4,
    "69":1500.2,
    "70":1115.0,
    "71":387.6,
    "72":700.0,
    "73":953.2,
    "74":304.0,
    "75":563.2,
    "76":251.0,
    "77":300.0,
    "78":500.4,
    "79":1729.0,
    "80":319.2,
    "81":344.0,
    "82":151.1,
    "83":500.0,
    "84":225.3,
    "85":300.1,
    "86":234.0,
    "87":1000.1,
    "88":242.0,
    "89":50.3,
    "90":600.1,
    "91":null,
    "92":105.3,
    "93":50.5,
    "94":127.4,
    "95":229.4,
    "96":128.2,
    "97":244.2,
    "98":188.2,
    "99":604.1,
    "100":77.7,
    "101":500.0,
    "102":500.0,
    "103":500.4,
    "104":92.7,
    "105":124.0,
    "106":800.3,
    "107":86.2,
    "108":500.3,
    "109":1860.4,
    "110":325.2,
    "111":275.0,
    "112":124.2,
    "113":225.3,
    "114":367.6,
    "115":351.7,
    "116":443.0,
    "117":277.4,
    "118":null,
    "119":332.7,
    "120":193.9,
    "121":100.7,
    "122":336.7,
    "123":344.9,
    "124":368.5,
    "125":271.0,
    "126":275.3,
    "127":382.0,
    "128":466.4,
    "129":384.0,
    "130":342.5,
    "131":357.5,
    "132":335.0,
    "133":327.5,
    "134":339.0,
    "135":189.0,
    "136":317.7,
    "137":318.0,
    "138":308.0,
    "139":222.4,
    "140":390.0,
    "141":null,
    "142":250.4,
    "143":335.4,
    "144":470.2,
    "145":270.8,
    "146":400.0,
    "147":361.9,
    "148":185.0,
    "149":409.4,
    "150":343.0,
    "151":353.2,
    "152":374.0,
    "153":275.8,
    "154":328.0,
    "155":368.5,
    "156":270.4,
    "157":270.4,
    "158":382.8,
    "159":240.9,
    "160":250.4,
    "161":260.4,
    "162":270.0,
    "163":280.9,
    "164":290.8,
    "165":300.4,
    "166":310.2,
    "167":320.4,
    "168":330.4
  }
}

In [57]:
data = {
  'Duration':{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [52]:
import json

In [59]:
msg=json.dumps(data) # json 형식의 문자열로

In [60]:
json.loads(msg) #json형식의 문자열을 dict

{'Duration': {'0': 60, '1': 60, '2': 60, '3': 45, '4': 45, '5': 60},
 'Pulse': {'0': 110, '1': 117, '2': 103, '3': 109, '4': 117, '5': 102},
 'Maxpulse': {'0': 130, '1': 145, '2': 135, '3': 175, '4': 148, '5': 127},
 'Calories': {'0': 409, '1': 479, '2': 340, '3': 282, '4': 406, '5': 300}}

In [65]:
df = pd.read_csv('data.csv')
df.tail(10)

     Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [67]:
df['Calories']

0       409.1
1       479.0
2       340.0
3       282.4
4       406.0
5       300.0
6       374.0
7       253.3
8       195.1
9       269.0
10      329.3
11      250.7
12      345.3
13      379.3
14      275.0
15      215.2
16      300.0
17        NaN
18      323.0
19      243.0
20      364.2
21      282.0
22      300.0
23      246.0
24      334.5
25      250.0
26      241.0
27        NaN
28      280.0
29      380.3
30      243.0
31      180.1
32      299.0
33      223.0
34      361.0
35      415.0
36      300.0
37      300.0
38      300.0
39      266.0
40      180.1
41      286.0
42      329.4
43      400.0
44      397.0
45      273.0
46      387.6
47      300.0
48      298.0
49      397.6
50      380.2
51      643.1
52      263.0
53      486.0
54      238.0
55      450.7
56      413.0
57      305.0
58      226.4
59      321.0
60     1376.0
61     1034.4
62      853.0
63      341.0
64      131.4
65      800.4
66      873.4
67      816.0
68      110.4
69     1500.2
70     1115.0
71      387.6
72      700.0
73      953.2
74      304.0
75      563.2
76      251.0
77      300.0
78      500.4
79     1729.0
80      319.2
81      344.0
82      151.1
83      500.0
84      225.3
85      300.0
86      234.0
87     1000.1
88      242.0
89       50.3
90      600.1
91        NaN
92      105.3
93       50.5
94      127.4
95      229.4
96      128.2
97      244.2
98      188.2
99      604.1
100      77.7
101     500.0
102     500.0
103     500.4
104      92.7
105     124.0
106     800.3
107      86.2
108     500.3
109    1860.4
110     325.2
111     275.0
112     124.2
113     225.3
114     367.6
115     351.7
116     443.0
117     277.4
118       NaN
119     332.7
120     193.9
121     100.7
122     336.7
123     344.9
124     368.5
125     271.0
126     275.3
127     382.0
128     466.4
129     384.0
130     342.5
131     357.5
132     335.0
133     327.5
134     339.0
135     189.0
136     317.7
137     318.0
138     308.0
139     222.4
140     390.0
141       NaN
142     250.4
143     335.4
144     470.2
145     270.8
146     400.0
147     361.9
148     185.0
149     409.4
150     343.0
151     353.2
152     374.0
153     275.8
154     328.0
155     368.5
156     270.4
157     270.4
158     382.8
159     240.9
160     250.4
161     260.4
162     270.0
163     280.9
164     290.8
165     300.0
166     310.2
167     320.4
168     330.4
Name: Calories, dtype: float64